### ISSUE TITLE
OpenHistoricalMap

### ISSUE THREAD

**Issue by 1ec5** [Zaczero/osm-revert#39]
The OpenHistoricalMap project would benefit from this tool too. The API is identical between OSM and OHM; it’s just a different domain and database. Would you be open to extending it to switch between the two APIs? Or would you suggest forking the project and standing up a separate instance? Thanks for your consideration!

**Comment by Zaczero** [comment]
I want to make the project universal and I am willing to work on the necessary changes. Let me know if you have a dedicated communication channel. We could work out the details on a call or something.

**Comment by 1ec5** [comment]
Glad to hear it! [We have lots of channels](https://wiki.openstreetmap.org/wiki/OpenHistoricalMap/Communication). 😛 Our developers monitor [the central issue tracker](https://github.com/OpenHistoricalMap/issues/issues/) closely. For discussion with the community, [the forum](https://forum.openhistoricalmap.org/) is probably the best place. Otherwise, feel free to reach out to me over [OSM private messages](https://www.openstreetmap.org/user/Minh%20Nguyen) or e-mail.[^email]

[^email]: My address is listed in openstreetmap/openstreetmap-website#5029 if you append .patch to the URL.

**Comment by Zaczero** [comment]
@1ec5 Please test it at https://ohm-revert.monicz.dev

**Comment by Zaczero** [comment]
I accidentally configured the service to turn off after 1 hour of runtime. I've fixed the issue, and the service is back up and running.

**Comment by 1ec5** [comment]
Thanks for setting this up! Unfortunately, it looks like OHM’s Overpass API endpoint doesn’t like the `/` at the end of the URL path. For example, [this query](https://overpass-api.openhistoricalmap.org/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0Awr%5B%22ref%22%3D%22US%2066%22%5D%3B%0Aout%20geom%3B) succeeds, but it fails with an HTTP 403 error if you [append a slash](https://overpass-api.openhistoricalmap.org/api/interpreter/?data=[out%3Ajson][timeout%3A25]%3B%0Awr[%22ref%22%3D%22US%2066%22]%3B%0Aout%20geom%3B).

```
[⛔] fetch_overpass failed
Traceback (most recent call last):
  File "/home/ohm-revert/osm_revert/main.py", line 58, in wrapper
    exit_code = func(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/osm_revert/main.py", line 152, in main
    diff = overpass.get_changeset_elements_history(changeset, steps, query_filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/osm_revert/overpass.py", line 220, in get_changeset_elements_history
    result = self._get_changeset_elements_history(http, changeset, steps, query_filter)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/osm_revert/overpass.py", line 257, in _get_changeset_elements_history
    partition_diff = fetch_overpass(http, partition_query)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/osm_revert/utils.py", line 45, in wrapper
    raise e
  File "/home/ohm-revert/osm_revert/utils.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/osm_revert/overpass.py", line 164, in fetch_overpass
    response.raise_for_status()  # TODO: return error message instead raise
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ohm-revert/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://overpass-api.openhistoricalmap.org/api/interpreter/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```

**Comment by Zaczero** [comment]
Hey please try again now! It should be fixed in b0596730cb6629c4dfdcfd48b1e351359c5d0afa

**Comment by 1ec5** [comment]
Thanks, it worked for [changeset 138,526](https://www.openhistoricalmap.org/changeset/138526). I opened OpenHistoricalMap/issues#891 to track handling the trailing slash.

ohm-revert still has some references to OSM, such as “Logging in to OpenStreetMap” in the log and the link to Pascal Neis’s osm-suspicious tool at the top. It’s just a cosmetic issue, but it had me worried for a moment that I’d be reverting an ancient OSM changeset by accident; maybe others would hesitate to use it for the same reason. Otherwise, I’m ready to add ohm-revert to OHM’s documentation on the wiki once you feel good about the state of things.

**Comment by Zaczero** [comment]
Yes I am aware of that. Ideally, the project names and links would be configurable too. I just didn't bother with that for now. 👍

**Comment by 1ec5** [comment]
https://forum.openhistoricalmap.org/t/introducing-ohm-revert-undo-changesets-from-the-comfort-of-your-browser/310

**Comment by 1ec5** [comment]
> ohm-revert still has some references to OSM

I split out #58. I’ll close this issue in favor of more specific issues going forward.
